#!/bin/bash
types=$(printf "Normal\nI2P/Onion" | dmenu -i -p "Type: ")

normal() {
  bm_path="$HOME/.bookmarks/.normalbookmarks"
  link=$(printf "quit" | dmenu -i -p "Link: ")
  [[ $link = "quit" ]] && exit 1 
  [[ $link = "" ]] && exit 1
  title=$(printf "untitled\nquit" | dmenu -i -p "Title: ")
  [[ $title = "quit" ]] && exit 1
  [[ $title = "" ]] && title="untitled"
  title=$(echo "$title" | sed "s/ /_/g")
  echo "$title $link" >> $bm_path
}

# Working thoughts
# paila bmpathgpg decrypt garne
# ani bmpath lai .onbookmarks ma rakhne
# take link
# link ma quit cha bhane quit garne or link empty cha bhane ni quit garne
# But first remove file on bm_path before quitting
# quit nabhaye get the title ani store in title variable
# same thing if title is quit and if empty set it untitled
# echo the title to the file replacing empty spaces with '_'
# rename the .onbookmarks.gpg file to .onbookmarks.gpg.bak
# encrypt the .onbookmarks file and if succesful remove .onbookmarks.gpg.bak and .onbookmarks

onion() { 
  bm_pathgpg="$HOME/.bookmarks/.onbookmarks.gpg" #renamed to bm_pathgpg
  gpg $bm_pathgpg #decrypts file and outputs .onbookmarks
  bm_path="$HOME/.bookmarks/.onbookmarks" 
  link=$(printf "quit" | dmenu -i -p "Link(onion/i2p): ")
  [[ $link = "quit" ]] && rm $bm_path && exit 1 
  [[ $link = "" ]] && rm $bm_path && exit 1
  title=$(printf "untitled\nquit" | dmenu -i -p "Title: ")
  [[ $title = "quit" ]] && rm $bm_path && exit 1
  [[ $title = "" ]] && title="untitled"
  title=$(echo "$title" | sed "s/ /_/g")
  echo "$title $link" >> $bm_path
  mv "$HOME/.bookmarks/.onbookmarks.gpg" "$HOME/.bookmarks/.onbookmarks.gpg.bak" # renaming the gpg file
  bm_pathgpgbak="$HOME/.bookmarks/.onbookmarks.gpg.bak"
  gpg -c --no-symkey-cache --cipher-algo AES256 $bm_path
  sleep 0.7
  [ -e $bm_pathgpg ] && rm $bm_path && rm $bm_pathgpgbak && exit 0
  mv "$HOME/.bookmarks/.onbookmarks.gpg.bak" "$HOME/.bookmarks/.onbookmarks.gpg" # renaming the bak file
  rm $bm_path
}

[[ $types = "Normal" ]] && normal && exit 0
[[ $types = "I2P/Onion" ]] && onion && exit 0
[[ $types = "" ]] && exit 1
